### ISSUE TITLE
Graph data

### ISSUE THREAD

**Issue by FrancescaFranzese** [epicprojects/blockchain-anomaly-detection#1]
Hi, 
I would like to know if there is a link or another way to download the graph file.

Thank you

**Comment by osancus** [comment]
@FrancescaFranzese can you be more specific, which file you want to download? is the transaction graph file?

https://www.kaggle.com/omershafiq/bitcoin-network-transactional-metadata

**Comment by FrancescaFranzese** [comment]
Yes, I downloaded the big .csv file that potentially allows me to create the graph but, since I don't have a lot of computational power, I'd like to have the .gml file.

Thanks for your help!

**Comment by osancus** [comment]
@FrancescaFranzese unfortunately, i do not have the gml file. Perhaps you can split csv into few peaces and load them one at a time. I also had trouble loading whole data to gephi however, i had the computation power to manage that. Moreover you can also read the data into a graph a structure via a python script and use that to create a visualisation as per you desire.
